version: 2.1

orbs:
  aws-cli: circleci/aws-cli@2.0.3

commands:
  destroy_environment:
    description: destroy the cloudformation environment
    steps:
      - run:
          name: delete cf environment
          when: on_fail
          command: |
            aws cloudformation delete-stack \
              --stack-name cicd-ansible-cf-${CIRCLE_WORKFLOW_ID:0:7}
  
jobs:
  create_infrastructure:
    docker:
    - image: amazon/aws-cli
    steps:
    - checkout
    - run:
        name: create cloudformation stack
        command: |
          aws cloudformation create-stack \
            --stack-name cicd-ansible-cf-${CIRCLE_WORKFLOW_ID:0:7} \
            --template-body file://cloudformation/template.yml \
            --capabilities "CAPABILITY_IAM" "CAPABILITY_NAMED_IAM" \
            --region us-east-1

  configure_infrastructure:
    docker:
    - image: python:3.7-alpine3.11
    steps:
    - checkout
    - add_ssh_keys:
        fingerprints:
        - "	f8:b0:66:b7:4a:ce:76:74:ca:28:26:13:08:73:1f:63"
    - run:
        name: installing ansible
        command: |
          apk add --update ansible
    - run:
        name: configure the server with ansible
        command: |
          ansible-playbook -i inventory.txt main-remote.yml

  smoke_test:
    docker: 
      - image: amazon/aws-cli
    steps:
      - run:
          name: failed step
          command: |
            if curl -s --head maelfosso.com
            then
              exit 0
            else
              exit 1
            fi
      - destroy_environment

workflows:
  ansible:
    jobs:
      - create_infrastructure
      # - configure_infrastructure
      - smoke_test
